### ISSUE TITLE
Show db update what's python version?

### ISSUE THREAD

**Issue by muji92** [nicoDs96/btc-flashing-demo#1]
![Screenshot_2024-10-28-02-39-46-909_com termux](https://github.com/user-attachments/assets/36ab36eb-af4f-4738-82d2-a8854d28b5e6)

**Comment by nicoDs96** [comment]
Hi @muji92 I am sorry but without additional context I do not understand the question. 
1. what are you doing when `nano db.py`  in the library folder? 
2. You have a clear warning stating about mismatch between library (0.7.0b1) and the actual db structure referring to tables of version v0.6.15 of the library, have you installed bitcoinlib multiple times?

btw my python version is 3.12

**Comment by muji92** [comment]
Oh oke im understand ... then what your bitcoinlib version for run the script...

**Comment by nicoDs96** [comment]
I am using version 0.6.15 as stated [here](https://nicods96.github.io/hi/bitcoin-flashing/)

**Comment by muji92** [comment]
But that version showing error

**Comment by nicoDs96** [comment]
@muji92 what error? In your screenshot you have two different version of the same library installed and you have edited the `db.py` file, can you give context and explain what are you doing? Otherwise I cannot help

**Comment by muji92** [comment]
Showing this error when i use bitcoinlib 0.6.15 how to solve?
![Screenshot_2024-10-29-19-57-47-663_com termux](https://github.com/user-attachments/assets/9be77e3c-8663-483f-877c-03c533f8aec9)

**Comment by muji92** [comment]
Owhh just on tesnet?

**Comment by muji92** [comment]
This is error' too
![Screenshot_2024-10-29-21-00-41-298_com termux](https://github.com/user-attachments/assets/83ff137c-78a1-4554-ba91-e9c3d6e6e257)

**Comment by nicoDs96** [comment]
@muji92 I think you are missing the point. If you are trying to scam someone, please let it go...

If you are trying to simply learn something, then read carefully the [blog post about this project](https://nicods96.github.io/hi/bitcoin-flashing/). You will learn that you cannot scam anyone. Then i suggest the [library documentation](https://bitcoinlib.readthedocs.io/en/latest/), how [the blockchain works](https://bitcoin.org/it/documento-bitcoin) and [what UTOX are](https://en.wikipedia.org/wiki/Unspent_transaction_output). 

I close the issue because I believe this dummy project has no issues but you might have some skill/kwnoledge issue that to me is impossible to fix. Time is all you need to study and practice about the topic.
